""" "3"

Revision ID: d96451c04eb3
Revises: 54dcc4403c92
Create Date: 2024-08-29 23:06:50.496400

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d96451c04eb3"
down_revision = "54dcc4403c92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "deleted_at")
    # ### end Alembic commands ###
