""" "4"

Revision ID: a840767db173
Revises: d96451c04eb3
Create Date: 2024-08-30 05:56:30.257274

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a840767db173"
down_revision = "d96451c04eb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bar_reports_user_id_fkey", "bar_reports", type_="foreignkey")
    op.drop_constraint("bar_reports_bar_id_fkey", "bar_reports", type_="foreignkey")
    op.create_foreign_key(
        None, "bar_reports", "bars", ["bar_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "bar_reports", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("bars", "admin_id")
    op.drop_constraint("likes_post_id_fkey", "likes", type_="foreignkey")
    op.drop_constraint("likes_user_id_fkey", "likes", type_="foreignkey")
    op.create_foreign_key(
        None, "likes", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "likes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("posts_bar_id_fkey", "posts", type_="foreignkey")
    op.drop_constraint("posts_user_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(None, "posts", "bars", ["bar_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "posts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("rsvps_post_id_fkey", "rsvps", type_="foreignkey")
    op.drop_constraint("rsvps_user_id_fkey", "rsvps", type_="foreignkey")
    op.create_foreign_key(
        None, "rsvps", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "rsvps", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("users_bar_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "bars", ["bar_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key("users_bar_id_fkey", "users", "bars", ["bar_id"], ["id"])
    op.drop_constraint(None, "rsvps", type_="foreignkey")
    op.drop_constraint(None, "rsvps", type_="foreignkey")
    op.create_foreign_key("rsvps_user_id_fkey", "rsvps", "users", ["user_id"], ["id"])
    op.create_foreign_key("rsvps_post_id_fkey", "rsvps", "posts", ["post_id"], ["id"])
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_user_id_fkey", "posts", "users", ["user_id"], ["id"])
    op.create_foreign_key("posts_bar_id_fkey", "posts", "bars", ["bar_id"], ["id"])
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key("likes_user_id_fkey", "likes", "users", ["user_id"], ["id"])
    op.create_foreign_key("likes_post_id_fkey", "likes", "posts", ["post_id"], ["id"])
    op.add_column(
        "bars", sa.Column("admin_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "bar_reports", type_="foreignkey")
    op.drop_constraint(None, "bar_reports", type_="foreignkey")
    op.create_foreign_key(
        "bar_reports_bar_id_fkey", "bar_reports", "bars", ["bar_id"], ["id"]
    )
    op.create_foreign_key(
        "bar_reports_user_id_fkey", "bar_reports", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
