""" "1"

Revision ID: 23383ae703b0
Revises:
Create Date: 2024-08-27 07:58:15.848949

"""



# revision identifiers, used by Alembic.
revision = "23383ae703b0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
