""" "5"

Revision ID: 36e99cf25357
Revises: a840767db173
Create Date: 2024-08-30 06:17:42.118794

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "36e99cf25357"
down_revision = "a840767db173"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bar_reports", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("bar_reports", "bar_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "bar_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column("bars", sa.Column("admin_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "bars", "users", ["admin_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("users_bar_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "bar_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("bar_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "users_bar_id_fkey", "users", "bars", ["bar_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "bars", type_="foreignkey")
    op.drop_column("bars", "admin_id")
    op.alter_column(
        "bar_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column("bar_reports", "bar_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bar_reports", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
